name: Build and Push Docker Image

on:
  push:
    branches:
      - "**"
#      - main

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read

jobs:
#  python-build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v4
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#
#      - name: Install Python dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install flake8 black
#
#      - name: Run flake8 (Python Linter)
#        run: |
#          flake8 . --max-line-length=120
#        continue-on-error: true
#
#      - name: Run black (Python Formatter)
#        run: |
#          black --check .
#        continue-on-error: true
#
#  docker-build-and-push:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v4
#
#      - name: Log in to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GHCR_PAT }}
#
#      - name: Build and push image to GHCR
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          tags: ghcr.io/${{ github.repository_owner }}/fastapi-app:latest
#          platforms: linux/amd64
  
  azure-login-and-deploy:
    runs-on: ubuntu-latest
    environment: CICD

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure Subscription Access
        run: az account show

      - name: List Container Apps
        run: az containerapp list --resource-group klub-inzenjera --output table

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name task-management-be \
            --resource-group klub-inzenjera \
            --image ghcr.io/${{ github.repository_owner }}/fastapi-app:latest \